kind: pipeline
name: test-on-avx2

platform:
  arch: amd64

steps:
- name: test
  image: rust:1
  environment:
    RUSTFLAGS: '-C target-cpu=native'
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
---

kind: pipeline
name: test-on-sse42

platform:
  arch: amd64

steps:
- name: test
  image: rust:1
  environment:
    RUSTFLAGS: '-C target-cpu=native -C target-feature=-avx2'
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

---

kind: pipeline
name: test-on-pre-sse42

platform:
  arch: amd64

steps:
- name: test
  image: rust:1
  environment:
    RUSTFLAGS: '-C target-cpu=native -C target-feature=-avx2,-sse4.2'
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

---

kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: rust:1
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
