[package]
name = "simdjson"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1" }
hashbrown = { version = "*", features = ["serde"] }
lazy_static = "1"
page_size = "0.4"

# Thisn should be  a dev dependecy but we can't make it optional then
simdjson-rust = { git = "https://github.com/SunDoge/simdjson-rust", optional = true }
jemallocator = { version = "*", optional = true }

[dev-dependencies]
proptest = "0.9.2"
serde_derive = "*"
serde_bytes = "*"
criterion = "0.2"
core_affinity = "*"


[[bench]]
name = "parse"
harness = false


[features]
default = ["swar-number-parsing"]
swar-number-parsing = []
no-inline = []
bench-serde = []
