[package]
name = "simdjson"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

[dependencies]
serde = "1"

[dev-dependencies]
serde_json = "1"
proptest = "0.9.2"

[features]
default = ["swar-number-parsing"]
swar-number-parsing = []
