[package]
name = "simd-json"
version = "0.1.15"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
exclude = [ "data/*" ]
license = "Apache-2.0/MIT"
description = "High performance JSON parser based on a port of simdjson"
repository = "https://github.com/Licenser/simdjson-rs"

[dependencies]
halfbrown = { version = "0.1" }
page_size = "0.4"
itoa = "0.4"
ryu = "0.2"
lexical = "2.1"

# serde compatibilty
serde = { version = "1.0", features = ["derive"], optional = true}
serde_json = { version = "1", optional = true}

# Thisn should be  a dev dependecy but we can't make it optional then
# simdjson-rust = { git = "https://github.com/SunDoge/simdjson-rust", optional = true }
jemallocator = { version = "0.3", optional = true }
perfcnt = { version = "0.4", optional = true }
getopts = { version = "0.2", optional = true }
colored = { version = "1.7", optional = true }




[dev-dependencies]
getopts = "0.2"
proptest = "0.9.2"
serde_derive = "1"
serde_bytes = "0.11"
criterion = "0.2"
#criterion = { path = "../criterion.rs" }
core_affinity = "0.5"


[[bench]]
name = "parse"
harness = false


[features]
default = ["swar-number-parsing", "serde_impl"]
# AVX2 compatibility -- TODO, figure out default
avx2 = []
# pre-AVX2 x64 SSE42 compatibility -- TODO, figure out default
sse42 = []
# use 8 number at once parsing strategy
swar-number-parsing = []
# serde compatibility
serde_impl = [ "serde", "serde_json", "halfbrown/serde" ]
# don't inline code - used for debugging
no-inline = []
# also bench serde in the benchmarks
bench-serde = []
# use branch hints - requires nightly :(
hints = [] # requires nightly
# for perf testing, used by the example
perf = ["perfcnt", "getopts", "colored"]


[[example]]
name = "perf"
