[package]
name = "simdjson"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
hashbrown = { version = "*", features = ["serde"] }

[dev-dependencies]
proptest = "0.9.2"
serde_derive = "*"
serde_bytes = "*"
assert_approx_eq = "1.1.0"

[features]
default = ["swar-number-parsing"]
swar-number-parsing = []
inline = []