name: Tests - Nightly

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rustflags:
          - '-C target-cpu=native'
          - '-C target-cpu=native -C target-feature=-avx2'
        features:
          - ''
          - '--features known-key'
          - '--features 128bit'
          - '--features beef'
          - '--features beef,known-key'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Update rustup
      if: ${{ matrix.os == 'windows-latest' }}
      run: rustup self update
      env:
        RUSTUP_UPDATE_ROOT: https://dev-static.rust-lang.org/rustup
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo build ${{ matrix.features }}
    - name: Run tests
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo test ${{ matrix.features }}
    - name: Run tests (alloc)
      if: matrix.features == ''
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo test --features alloc
