name: Quality

on: [push]

jobs:
  clippy_check:
    strategy:
      matrix:
        rustflags:
          - "-C target-cpu=native"
          - "-C target-cpu=native -C target-feature=-avx2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Validate cargo format
        run: cargo fmt -- --check
      - name: Install clippy
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all
  tarpaulin-sse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config cmake zlib1g-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install tarpaulin
        run: bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      - name: run tarpaulin
        env:
          RUSTFLAGS: "-C target-cpu=native -C target-feature=-avx2"
          PROPTEST_CASES: 512
        run: cargo tarpaulin -v --features no-inline --out Xml && cp cobertura.xml sse.xml
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./sse.xml
          flags: e
  tarpaulin-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config cmake zlib1g-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install tarpaulin
        run: bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      - name: run tarpaulin
        env:
          RUSTFLAGS: "-C target-cpu=native"
          PROPTEST_CASES: 512
        run: cargo tarpaulin -v --features no-inline --out Xml && cp cobertura.xml avx.xml
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./avx.xml
          flags: avx2
  tarpaulin-sse-known-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config cmake zlib1g-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install tarpaulin
        run: bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      - name: run tarpaulin
        env:
          RUSTFLAGS: "-C target-cpu=native -C target-feature=-avx2"
          PROPTEST_CASES: 512
        run: cargo tarpaulin -v --features no-inline known-key --out Xml && cp cobertura.xml sse-known-key.xml
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./sse-known-key.xml
          flags: sseKnownKey
  tarpaulin-avx2-known-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config cmake zlib1g-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install tarpaulin
        run: bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      - name: run tarpaulin
        env:
          RUSTFLAGS: "-C target-cpu=native"
          PROPTEST_CASES: 512
        run: cargo tarpaulin -v --features no-inline known-key --out Xml && cp cobertura.xml avx2-known-key.xml
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./avx2-known-key.xml
          flags: avx2KnownKey
